### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by Rotemy** [tonswap/tonswap-contracts#1]
- Multi pairs but not multi hop
- AMM (Uniswap v2)
- User story - New project with token that is not listed anywhere
- One side of the pair is native currency (right now only TON)
- Add liquidity and stake
- Add liquidity and no stake
- Claim rewards
- Unstake and remove liquidity
- Unstake without remove liquidity 
- Swap (in & out)
- TRC20 (transfer)
- Admin (alloc point, reward tokens, deposit rewards)

- Find a bot name

- Flow 
- (who are you?)
- Show tokens / disconnect
- Swap / liquidity
- Add / Remove liquidity / claim

**Comment by tvorogme** [comment]
Cool mvp stuff
